name: Tests

on:
  push:
    branches:
      - master
      - beta
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.1
      - name: yarn install and test
        run: |
          yarn install
          yarn test
        env:
          CI: true
